### ISSUE TITLE
Drop the NixOS module as it's not needed anymore

### ISSUE THREAD

**Issue by jiriks74** [lelgenio/dzgui-nix#8]
Hi,
[I've made my own flake for running `dzgui`](https://github.com/jiriks74/dzgui.flake) and `aclist` made me aware of yours.

I see that you have a NixOS module for setting `vm.max_map_count`. This made me look into it more and I've ran across this issue: NixOS/nixpkgs#238412. There I saw that NixOS has increased the default value to `1048576` in NixOS/nixpkgs#238459.

With this being merged on 5. 8. 2023 NixOS versions with the lower values are deprecated so the NixOS module for setting this value isn't needed anymore.

I think that dropping the module would be beneficial for your users as they can now just include the package or use
`nix run "github:lelgenio/dzgui-nix"` to get `dzgui` running.

**Comment by lelgenio** [comment]
Thanks for the reminder! I've deprecated the module for now, so people are not forced to update their configs right now.

> [I've made my own flake for running `dzgui`](https://github.com/jiriks74/dzgui.flake) and `aclist` made me aware of yours.

Duplicate work 😅 

Maybe you'd like to merge both repositories?

**Comment by jiriks74** [comment]
> Duplicate work 😅

Yeah, I've figured. I've finished my work as it's already been almost done at that point and I've seen that we had different approaches.

I've gone more the `package` route while you, as far as I understand it, packaged only the script itself (`dzgui.sh`) and let it manage everything in `~/.local/share/dzgui`.

My approach was modifying parts of the project so that I could package everything so there wouldn't be any issues with version mismatch, `dzgui.sh` creating things it shouldn't (it creates a file at `~/.local/applications/DZGUI.desktop` which overwrites the system one needed to run the package and that causes `dzgui` not launching from the desktop), etc.

I've also packaged both `stable` and `testing` and I overwrite the branches based on the package used, so it doesn't load the branch used from the config file (strange to save it there IMHO but whatever). I've also remove branch switching option from the UI so that users won't have a useless option in there.

I've also set up some weird things (compared to *normal* packaging) like getting the package source from flake inputs (easier updates), etc.

Also I've tried to do everything in a way that allows users to `nix run "github:jiriks74/dzgui.flake"` so they won't need to bother with setting up a custom package in their config if they want to play right away (eg. when I wanted to play and figured out that there's no working launcher on NixOS and I had to set this up XD - didn't know about this at that time).

---

Feel free to go through my code but ***I warned you*** so I'm not responsible for any *seeing horrifying nix practices* related heart attacks 😂.

**Comment by lelgenio** [comment]
> Yeah, I've figured. I've finished my work as it's already been almost done at that point and I've seen that we had different approaches.
> 
> I've gone more the `package` route while you, as far as I understand it, packaged only the script itself (`dzgui.sh`) and let it manage everything in `~/.local/share/dzgui`.

To be honest, it ended up working like that by accident. When I originally created the package, `dzgui` only contained `dzgui.sh`, it's GUI was created using only zenity prompts. The "Main GUI" built with python was added after that.

I did  fiddle with trying to achieve what you did, but the project was being updated too often for me to create something that would work correctly across updates.

> I've also packaged both `stable` and `testing` and I overwrite the branches based on the package used, so it doesn't load the branch used from the config file (strange to save it there IMHO but whatever). I've also remove branch switching option from the UI so that users won't have a useless option in there.

My intentions were to eventually upstream to `nixpkgs`, but there's still much to be talked with aclist to see if that's feasible. So I only added support for the stable branch.

> I've also set up some weird things (compared to _normal_ packaging) like getting the package source from flake inputs (easier updates), etc.

It's easier yes, I originally did that, but it locks out people who don't use flakes, I later changed it and added an update script that would work if put on `nixpkgs` too.

> Also I've tried to do everything in a way that allows users to `nix run "github:jiriks74/dzgui.flake"` so they won't need to bother with setting up a custom package in their config if they want to play right away.

That actually should work here too, it (was) just not documented.

**Comment by jiriks74** [comment]
> My intentions were to eventually upstream to `nixpkgs`

I've talked about this with him and as far as I understand the stable branch isn't getting updates as often as it did. So it looks like the `stable` branch can be upstreamed without it being updated every week. I'll be watching how the project's update cadance to see whether it's possible.

> `dzgui` only contained `dzgui.sh`, it's GUI was created using only zenity prompts. The "Main GUI" built with python was added after that.

I think I used it at that time but I didn't use NixOS. Once I came back to DayZ the UI was already in GTK.

> it locks out people who don't use flakes

That's a good point actually. What would be your approach to package both branches? The only way that comes to mind is having 2 package files which leaves quite a lot of duplicated code. I don't like that but it's probably the best way.

I'd like to modify your usage script, as I haven't gotten into automating this yet, but I think we chose incompatible licenses. Is that a concern for you or it's alright if I use something from your work?

**Comment by lelgenio** [comment]
> I'd like to modify your usage script, as I haven't gotten into automating this yet, but I think we chose incompatible licenses. Is that a concern for you or it's alright if I use something from your work?

AGHR, licenses. It's not that we choose incompatible licenses, it's that I choose the wrong license :laughing:.

I'm the only author of the update script, so I grant you the permission to use that code with the MIT license.

I'll see about relicensing this project, only 2 people have previously contributed, so it should not be hard to do that.

**Comment by lelgenio** [comment]
Hi @jiriks74, do you happen to have an archive of the dzgui/dztui repository?

It appears the repository/aclist's account have been deleted: https://github.com/aclist/dztui

**Comment by lelgenio** [comment]
Update: I had an old fork and github miraculously let me sync with the latest version: https://github.com/lelgenio/dztui

**Comment by jiriks74** [comment]
> Hi @jiriks74, do you happen to have an archive of the dzgui/dztui repository?
> 
> It appears the repository/aclist's account have been deleted: https://github.com/aclist/dztui

I do. I am also in contact with @aclist.
Sadly the fork won't work for you without some work on your side with how your package is set up as it will try to pull files that *don't exist* (aren't publicly accessible) anymore

> Update: I had an old fork and github miraculously let me sync with the latest version: https://github.com/lelgenio/dztui

It did because the account isn't entirely gone it's just not showing to anyone except @aclist himself.

I should have a working flake within the next few minutes with the new repository at https://codeberg.org/aclist/dztui

**Comment by jiriks74** [comment]
@lelgenio My flake is now working and it seems that upstream has been fixed to make `dzgui` work with the new host (Codeberg vs GitHub). I've tested only the basic functionality but everything seems to be fine as far as the code itself goes.

**Comment by jiriks74** [comment]
Ok. As upstream is patched to use the new source host it should be working for you as well if you change your source.

**Comment by aclist** [comment]
My account is working again; apparently it was due to some automated anti-bot script that turned up a false positive.

I'll be cleaning up the work from yesterday and bringing in the changes from Codeberg over to GitHub, but the logic going forward for in-app version updates will be to check the GitHub repo first and, in the event of an outage, check the Codeberg repo second (contents will be the same). Not sure whether you want to base off a single source or add your own fallback logic, too.

> My intentions were to eventually upstream to nixpkgs, but there's still much to be talked with aclist to see if that's feasible. So I only added support for the stable branch.

Let me know how I can help.

**Comment by aclist** [comment]
@lelgenio @jiriks74 

I'm planning some changes to DZGUI's approach to packaging in the distant future that I'm bringing up here in case they have some impact on your own packaging system.

As you know, DZGUI began life as a Bash script and used Zenity to bootstrap its UI before switching over wholesale to GTK. Now DZGUI is in a "Ship of Theseus" mode: before, only the front-facing UI was in Python and GTK, with all of the computation still being delegated to bits and bobs of the original Bash scripts.

This year I've replaced a lot of the legacy Bash logic with native Python functionality so that the UI and controller are still loosely coupled, but the backend is driven by custom Python modules rather than a collection of Bash functions. This is not finished, but I've scrubbed a lot of the legacy stuff. Some of this had to be done anyway to enable new features.

Once this is fully scrubbed, I plan to replace the startup script (also Bash) with a more friendly setup/configuration wizard that guides users through the process of setting up their first-time configs, which some users still struggle with. This will also be in Python, so the final result should be a collection of Python code that can be sandwiched together without the need for extra Bash glue. 

Anyway, the point is that once that is done, my thinking is to use a more structured packaging/release system and let users point pipx at the repository so that installation can go right into the system or a Python virtual environment, rather than a shell script that is just orphaned on the system. Over-the-air updates will still be provided, but they would point to the releases page rather than to raw files inside the repository, and the unpacking logic can be handled by the setup tools. *We may still need to provide a shell script shim for Steam Deck users to help with initial installation.

I expect the refactoring to continue throughout the end of the year for the backend parts, and the setup wizard will probably bleed into next year. So I'm not putting a firm date on it, but maybe around Q1-Q2 of next year, I'd like to migrate to this new install process. I think this should generally be more flexible than hand-rolling a Makefile.

Let me know if there are any caveats here with regard to nixOS or if there's anything else you'd like to add.

@jiriks74  Again, I can't thank you enough for the help during the cutover process when creating the CodeBerg backup. That was a very stressful moment, and something similar actually happened about a month ago--GitHub's database went awry for about 24 hours, and the contents of some branches were pointing to other branches instead (old data appearing in new branches). That was a sitewide issue, but still exposes the need to be vigilant.

I'm still doing a lot of heavy refactoring at the moment, but you're certainly welcome to open up any loose threads or make other contributions once the Ship of Theseus sets sail...I believe we left a couple of unfinished topics on the cutting room floor. At your leisure, of course.

**Comment by jiriks74** [comment]
> Anyway, the point is that once that is done, my thinking is to use a more structured packaging/release system

Have you considered setting up the project with `setup.py` or `pyproject.toml`? [It should make the packaging using `nix` easier](https://wiki.nixos.org/wiki/Python#With_pyproject.toml) but probably also for others. Generally standardized packaging leads to less headaches both for devs and users.

The only thing we need is the ability to launch the launcher without an installer. A setup wizard is fine but an installer would most likely crash as binaries are in unexpected places and some parts of the system are read only.

> Again, I can't thank you enough for the help during the cutover process when creating the CodeBerg backup.

You're welcome, I'm glad to have helped. It was a great exercise for me that I'll probably have some use for in the future.

> something similar actually happened about a month ago--GitHub's database went awry for about 24 hours, and the contents of some branches were pointing to other branches instead

Well I'm glad that it didn't write any changes to the mirror because it's something that could have been easily done by triggering the mirror job.

> I believe we left a couple of unfinished topics on the cutting room floor.

I don't have as much free time for playing games as I used to, even less for playing DayZ specifically. but I'll probably get it running again and look through the issues we made and try to help resolve the unfinished things.

---

It's great to see you still working on the project and making it better! Since you'll be moving to a more *stable* release process I think that I could even get `dzgui` into `nixpkgs` if the resulting build script won't be something insane.

**Comment by aclist** [comment]
> Have you considered setting up the project with setup.py or pyproject.toml?

Yes, these approaches are complementary to each other; pipx expects a pyproject.toml anyway. Currently, users pipe an install script into the terminal and it fetches a bunch of files and moves them around, but it doesn't create a commandline entrypoint or an "installation" per se; the script just resides on the system. Besides being brittle, I also don't like this because it demands extra trust from the user to assume the install script is doing something legitimate.

For the average user, switching to something like pipx means:

- They can invoke a single, simple command to install
- Application will be installed into its own venv with necessary dependencies
- Won't pollute global system files
- Doesn't require sudo escalation
- Provides a sane CLI entrypoint ('dzgui') that can be used from anywhere

Steam Deck users will still need an extra shim, because pip/pipx is not installed OOTB.

So at this point you would have several options coming from the same source:
1. Clone repo and install locally (pip/pipx)
2. Install locally direct from repo or release URL (pip/pipx)
3. Use bootstrap script to install (Steam Deck)
4. Use system package manager (nixOS)

> The only thing we need is the ability to launch the launcher without an installer. A setup wizard is fine but an installer would most likely crash as binaries are in unexpected places and some parts of the system are read only.

The new setup wizard will just concern itself with making sure the user's configuration file is set up correctly.

The current process for auto-updating is like this:

- Check for version/checksum mismatches with local files.
- If user agrees to update, fetch the relevant files one by one, copying them to the relevant directory

The new auto-update process would be something like:

- Check for release mismatch.
- If user agrees to update, fetch the entire release archive and update the existing venv in place.

Since this logic would be localized to essentially one or two lines now, I could check `/etc/os-release` and abort the update step if the contents match a nixOS identifier, unless you have some other suggestion.
